name = "tabiat-olami-mini-app"
main = "src/worker.js"
compatibility_date = "2026-10-05"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "tabiat-db"
database_id = "d92fab67-05a2-4fde-9563-8388b8d59108"
migrations_dir = "migrations"

[vars]
PUBLIC_APP_URL = "https://tabiat-olami.hcsacademya.workers.dev"
