BEGIN TRANSACTION;
INSERT INTO categories(id,name,icon,sort_order) VALUES (1,'Yovvoyi hayvonlar','🦁',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (1,'Sher','Sher haqida qisqa ma’lumot.','/images/01_01_sher.svg',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (1,'Fil','Fil haqida qisqa ma’lumot.','/images/01_02_fil.svg',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (1,'Jirafa','Jirafa haqida qisqa ma’lumot.','/images/01_03_jirafa.svg',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (1,'Zebra','Zebra haqida qisqa ma’lumot.','/images/01_04_zebra.svg',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (1,'Maymun','Maymun haqida qisqa ma’lumot.','/images/01_05_maymun.svg',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (1,'Karkidon','Karkidon haqida qisqa ma’lumot.','/images/01_06_karkidon.svg',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (1,'Begemot','Begemot haqida qisqa ma’lumot.','/images/01_07_begemot.svg',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (1,'Kiyik','Kiyik haqida qisqa ma’lumot.','/images/01_08_kiyik.svg',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (1,'Gorilla','Gorilla haqida qisqa ma’lumot.','/images/01_09_gorilla.svg',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (1,'Kenguru','Kenguru haqida qisqa ma’lumot.','/images/01_10_kenguru.svg',10);
INSERT INTO categories(id,name,icon,sort_order) VALUES (2,'Yirtqich hayvonlar','🐯',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (2,'Yo‘lbars','Yo‘lbars haqida qisqa ma’lumot.','/images/02_01_yo_lbars.svg',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (2,'Bo‘ri','Bo‘ri haqida qisqa ma’lumot.','/images/02_02_bo_ri.svg',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (2,'Tulki','Tulki haqida qisqa ma’lumot.','/images/02_03_tulki.svg',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (2,'Qoplon','Qoplon haqida qisqa ma’lumot.','/images/02_04_qoplon.svg',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (2,'Gepard','Gepard haqida qisqa ma’lumot.','/images/02_05_gepard.svg',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (2,'Ayiq','Ayiq haqida qisqa ma’lumot.','/images/02_06_ayiq.svg',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (2,'Sirtlon','Sirtlon haqida qisqa ma’lumot.','/images/02_07_sirtlon.svg',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (2,'Timsoh','Timsoh haqida qisqa ma’lumot.','/images/02_08_timsoh.svg',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (2,'Ilon','Ilon haqida qisqa ma’lumot.','/images/02_09_ilon.svg',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (2,'Burgut','Burgut haqida qisqa ma’lumot.','/images/02_10_burgut.svg',10);
INSERT INTO categories(id,name,icon,sort_order) VALUES (3,'Baliqlar','🐟',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (3,'Oltinbaliq','Oltinbaliq haqida qisqa ma’lumot.','/images/03_01_oltinbaliq.svg',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (3,'Akula','Akula haqida qisqa ma’lumot.','/images/03_02_akula.svg',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (3,'Kit akulasi','Kit akulasi haqida qisqa ma’lumot.','/images/03_03_kit_akulasi.svg',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (3,'Skat','Skat haqida qisqa ma’lumot.','/images/03_04_skat.svg',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (3,'Laqqa baliq','Laqqa baliq haqida qisqa ma’lumot.','/images/03_05_laqqa_baliq.svg',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (3,'Forel','Forel haqida qisqa ma’lumot.','/images/03_06_forel.svg',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (3,'Losos','Losos haqida qisqa ma’lumot.','/images/03_07_losos.svg',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (3,'Sazan','Sazan haqida qisqa ma’lumot.','/images/03_08_sazan.svg',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (3,'Tuna','Tuna haqida qisqa ma’lumot.','/images/03_09_tuna.svg',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (3,'Delfin','Delfin haqida qisqa ma’lumot.','/images/03_10_delfin.svg',10);
INSERT INTO categories(id,name,icon,sort_order) VALUES (4,'Qushlar','🐦',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (4,'Burgut','Burgut haqida qisqa ma’lumot.','/images/04_01_burgut.svg',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (4,'Boyo‘g‘li','Boyo‘g‘li haqida qisqa ma’lumot.','/images/04_02_boyo_g_li.svg',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (4,'Qarg‘a','Qarg‘a haqida qisqa ma’lumot.','/images/04_03_qarg_a.svg',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (4,'Kabutar','Kabutar haqida qisqa ma’lumot.','/images/04_04_kabutar.svg',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (4,'Laylak','Laylak haqida qisqa ma’lumot.','/images/04_05_laylak.svg',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (4,'Qaldirg‘och','Qaldirg‘och haqida qisqa ma’lumot.','/images/04_06_qaldirg_och.svg',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (4,'To‘tiqush','To‘tiqush haqida qisqa ma’lumot.','/images/04_07_to_tiqush.svg',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (4,'Tovus','Tovus haqida qisqa ma’lumot.','/images/04_08_tovus.svg',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (4,'Oqqush','Oqqush haqida qisqa ma’lumot.','/images/04_09_oqqush.svg',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (4,'Flamingo','Flamingo haqida qisqa ma’lumot.','/images/04_10_flamingo.svg',10);
INSERT INTO categories(id,name,icon,sort_order) VALUES (5,'Hasharotlar','🐝',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (5,'Asalari','Asalari haqida qisqa ma’lumot.','/images/05_01_asalari.svg',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (5,'Kapalak','Kapalak haqida qisqa ma’lumot.','/images/05_02_kapalak.svg',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (5,'Chumoli','Chumoli haqida qisqa ma’lumot.','/images/05_03_chumoli.svg',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (5,'Qo‘ng‘iz','Qo‘ng‘iz haqida qisqa ma’lumot.','/images/05_04_qo_ng_iz.svg',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (5,'Chigirtka','Chigirtka haqida qisqa ma’lumot.','/images/05_05_chigirtka.svg',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (5,'Ninachi','Ninachi haqida qisqa ma’lumot.','/images/05_06_ninachi.svg',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (5,'Pashsha','Pashsha haqida qisqa ma’lumot.','/images/05_07_pashsha.svg',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (5,'Chivin','Chivin haqida qisqa ma’lumot.','/images/05_08_chivin.svg',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (5,'Qurt','Qurt haqida qisqa ma’lumot.','/images/05_09_qurt.svg',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (5,'Qo‘ng‘izcha','Qo‘ng‘izcha haqida qisqa ma’lumot.','/images/05_10_qo_ng_izcha.svg',10);
INSERT INTO categories(id,name,icon,sort_order) VALUES (6,'Mevalar','🍎',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (6,'Olma','Olma haqida qisqa ma’lumot.','/images/06_01_olma.svg',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (6,'Nok','Nok haqida qisqa ma’lumot.','/images/06_02_nok.svg',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (6,'Apelsin','Apelsin haqida qisqa ma’lumot.','/images/06_03_apelsin.svg',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (6,'Banan','Banan haqida qisqa ma’lumot.','/images/06_04_banan.svg',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (6,'Uzum','Uzum haqida qisqa ma’lumot.','/images/06_05_uzum.svg',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (6,'Anor','Anor haqida qisqa ma’lumot.','/images/06_06_anor.svg',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (6,'Shaftoli','Shaftoli haqida qisqa ma’lumot.','/images/06_07_shaftoli.svg',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (6,'Gilos','Gilos haqida qisqa ma’lumot.','/images/06_08_gilos.svg',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (6,'Qulupnay','Qulupnay haqida qisqa ma’lumot.','/images/06_09_qulupnay.svg',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (6,'Mango','Mango haqida qisqa ma’lumot.','/images/06_10_mango.svg',10);
INSERT INTO categories(id,name,icon,sort_order) VALUES (7,'Daraxtlar','🌳',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (7,'Terak','Terak haqida qisqa ma’lumot.','/images/07_01_terak.svg',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (7,'Chinor','Chinor haqida qisqa ma’lumot.','/images/07_02_chinor.svg',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (7,'Archa','Archa haqida qisqa ma’lumot.','/images/07_03_archa.svg',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (7,'Qayin','Qayin haqida qisqa ma’lumot.','/images/07_04_qayin.svg',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (7,'Eman','Eman haqida qisqa ma’lumot.','/images/07_05_eman.svg',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (7,'Qarag‘ay','Qarag‘ay haqida qisqa ma’lumot.','/images/07_06_qarag_ay.svg',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (7,'Tol','Tol haqida qisqa ma’lumot.','/images/07_07_tol.svg',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (7,'Olma daraxti','Olma daraxti haqida qisqa ma’lumot.','/images/07_08_olma_daraxti.svg',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (7,'O‘rik daraxti','O‘rik daraxti haqida qisqa ma’lumot.','/images/07_09_o_rik_daraxti.svg',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (7,'Tut daraxti','Tut daraxti haqida qisqa ma’lumot.','/images/07_10_tut_daraxti.svg',10);
INSERT INTO categories(id,name,icon,sort_order) VALUES (8,'Gullar','🌸',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (8,'Atirgul','Atirgul haqida qisqa ma’lumot.','/images/08_01_atirgul.svg',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (8,'Lola','Lola haqida qisqa ma’lumot.','/images/08_02_lola.svg',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (8,'Moychechak','Moychechak haqida qisqa ma’lumot.','/images/08_03_moychechak.svg',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (8,'Binafsha','Binafsha haqida qisqa ma’lumot.','/images/08_04_binafsha.svg',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (8,'Nargiz','Nargiz haqida qisqa ma’lumot.','/images/08_05_nargiz.svg',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (8,'Rayhon guli','Rayhon guli haqida qisqa ma’lumot.','/images/08_06_rayhon_guli.svg',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (8,'Boychechak','Boychechak haqida qisqa ma’lumot.','/images/08_07_boychechak.svg',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (8,'Orxideya','Orxideya haqida qisqa ma’lumot.','/images/08_08_orxideya.svg',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (8,'Kungaboqar','Kungaboqar haqida qisqa ma’lumot.','/images/08_09_kungaboqar.svg',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (8,'Chinnigul','Chinnigul haqida qisqa ma’lumot.','/images/08_10_chinnigul.svg',10);
INSERT INTO categories(id,name,icon,sort_order) VALUES (9,'O‘simliklar','🌿',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (9,'Aloe vera','Aloe vera haqida qisqa ma’lumot.','/images/09_01_aloe_vera.svg',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (9,'Kaktus','Kaktus haqida qisqa ma’lumot.','/images/09_02_kaktus.svg',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (9,'Yalpiz','Yalpiz haqida qisqa ma’lumot.','/images/09_03_yalpiz.svg',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (9,'Rayhon','Rayhon haqida qisqa ma’lumot.','/images/09_04_rayhon.svg',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (9,'Shivit','Shivit haqida qisqa ma’lumot.','/images/09_05_shivit.svg',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (9,'Petrushka','Petrushka haqida qisqa ma’lumot.','/images/09_06_petrushka.svg',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (9,'Makkajo‘xori','Makkajo‘xori haqida qisqa ma’lumot.','/images/09_07_makkajo_xori.svg',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (9,'Bug‘doy','Bug‘doy haqida qisqa ma’lumot.','/images/09_08_bug_doy.svg',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (9,'Guruch o‘simligi','Guruch o‘simligi haqida qisqa ma’lumot.','/images/09_09_guruch_o_simligi.svg',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (9,'Kartoshka','Kartoshka haqida qisqa ma’lumot.','/images/09_10_kartoshka.svg',10);
INSERT INTO categories(id,name,icon,sort_order) VALUES (10,'Uy hayvonlari','🐾',10);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (10,'Mushuk','Mushuk haqida qisqa ma’lumot.','/images/10_01_mushuk.svg',1);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (10,'It','It haqida qisqa ma’lumot.','/images/10_02_it.svg',2);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (10,'Ot','Ot haqida qisqa ma’lumot.','/images/10_03_ot.svg',3);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (10,'Sigir','Sigir haqida qisqa ma’lumot.','/images/10_04_sigir.svg',4);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (10,'Qo‘y','Qo‘y haqida qisqa ma’lumot.','/images/10_05_qo_y.svg',5);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (10,'Echki','Echki haqida qisqa ma’lumot.','/images/10_06_echki.svg',6);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (10,'Quyon','Quyon haqida qisqa ma’lumot.','/images/10_07_quyon.svg',7);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (10,'Tovuq','Tovuq haqida qisqa ma’lumot.','/images/10_08_tovuq.svg',8);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (10,'O‘rdak','O‘rdak haqida qisqa ma’lumot.','/images/10_09_o_rdak.svg',9);
INSERT INTO items(category_id,name,description,image_url,sort_order) VALUES (10,'Eshak','Eshak haqida qisqa ma’lumot.','/images/10_10_eshak.svg',10);
COMMIT;